### ISSUE TITLE
sklearn compatible interface

### ISSUE THREAD

**Issue by fkiraly** [astrogilda/tsbootstrap#44]
umbrella issue for `sklearn` / `skbase` compatible interfaces

- [x] `__init__` compatibility for main classes - #51, related #43 
    * all args in main class
    * config deprecated
- [x] `BaseObject` inheritance for main classes - #8
- [x] tested in `scikit-base` test framework - #9 
    * including: ensure that current classes - post #51 - pass `skbase` tests. This can lead to further actionables.
